
#
# see: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options
#

version: '2.1'
services:
  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      #- IMAGE_ARG_APT_MIRROR=${IMAGE_ARG_APT_MIRROR}
      - IMAGE_ARG_APT_MIRROR=${IMAGE_ARG_APT_MIRROR:-mirrors.163.com}
      - IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER}
    command: ["start-notebook.sh"]
    container_name: ${CONTAINER_HOST_NAME:-jupyter-notebook}
    environment:
    #- CHOWN_EXTRA="<some dir>,<some other dir>"
    #- CHOWN_EXTRA_OPTS=-R
    - CHOWN_HOME=yes
    - CHOWN_HOME_OPTS=-R
    - GEN_CERT=yes
    - GRANT_SUDO=yes
    - JUPYTER_LAB_ENABLE=${JUPYTER_LAB_ENABLE:-no}
    - NB_GID=1000
    - NB_GROUP=${NB_USER:-jovyan}
    - NB_UID=1000
    - NB_USER=${NB_USER:-jovyan}
    hostname: ${CONTAINER_HOST_NAME:-jupyter-notebook}
    image: ${IMAGE_PREFIX:-infratop}/jupyter-notebook:${IMAGE_TAG:-177037d09156}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.jupyter}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/jupyter/standalone}
    networks:
      local-network:
        ipv4_address: 172.16.238.100
        #ipv6_address: 2001:3984:3989::100
    ports:
    - "${SERVER_PORT:-8888}:8888"
    restart: always
    volumes:
    - cert:/etc/ssl/notebook
    - log:/home/${NB_USER:-jovyan}/log
    - work:/home/${NB_USER:-jovyan}/work

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  cert:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/cert
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
  work:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/work
      o: bind
